## Beauty of `Numpy` and `Dot Product`

In [ ]:
import numpy as np

### Implementing `Neuron` from Scratch

In [4]:
## inputs and weights to be defined
inputs = np.random.randint(0.5,2,4)
weights = np.random.randint(0.5,2.5,4)
bias = np.random.rand(1)

outputs = np.dot(inputs, weights) + bias
inputs, weights, bias, outputs

(array([1, 0, 1, 1]),
 array([0, 0, 0, 0]),
 array([0.38110957]),
 array([0.38110957]))

### Implementing `Layers` from Scratch

In [5]:
inputs = np.random.randint(1,2,(4,1)) ##neurons
weights = np.random.randint(1,2,(3,4)) ## weights
bias = np.random.randint(0,2,(3,1)) ##bias
outputs = np.dot(weights, inputs)
inputs, weights, bias, outputs+bias


(array([[1],
        [1],
        [1],
        [1]]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]),
 array([[1],
        [0],
        [0]]),
 array([[5],
        [4],
        [4]]))

In [6]:
inputs = np.random.randint(1,2,(1,4)) ##neurons
weights = np.random.randint(1,2,(3,4)) ## weights
bias = np.random.randint(0,2,(1,3)) ##bias
outputs = np.dot(inputs, weights.T)
inputs, weights, bias, outputs+bias

(array([[1, 1, 1, 1]]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]),
 array([[1, 1, 1]]),
 array([[5, 5, 5]]))

### Implementing `Batch` from Scratch

In [10]:
inputs = np.random.randint(0,2,(4,3)) ## inputs [Different Inputs]
weights = np.random.randint(0,2,(3,4)) ## Weights [Different Weights]
bias = np.random.randint(0,2,(3,1)) ## bias

outputs = np.dot(weights, inputs) + bias
inputs, weights, bias, outputs

(array([[1, 0, 1],
        [1, 1, 1],
        [1, 0, 0],
        [0, 0, 1]]),
 array([[1, 0, 0, 1],
        [1, 1, 0, 0],
        [0, 1, 1, 1]]),
 array([[1],
        [0],
        [0]]),
 array([[2, 1, 3],
        [2, 1, 2],
        [2, 1, 2]]))