## Coding Multiple `Neural Network layer` and Stacking them together

In [1]:
import numpy as np 

In [14]:
## inputs, weights, bias
inputs = np.random.randint(0,2,(3,4)) ## inputs
weights_1 = np.random.randint(0,2,(3,4)) ## weights - Hidden Layer 1
bias_1 = np.random.randint(0,2,(3,1)) ## bias - Hidden Layer 1

outputs_1 = np.dot(weights_1, inputs.transpose()) + bias_1
print("Hidden Layer - 1", "\n")
print(inputs, "\n", weights_1, "\n", bias_1, "\n", outputs_1)
print("\n")
weights_2 = np.random.randint(0,2,(2,3)) ## weights - Hidden Layer 2
bias_2 = np.random.randint(0,2,(3,1)) ## bias - Hidden Layer 2
outputs_2 = np.dot(outputs_1, weights_2.T) + bias_2
print("Hidden Layer - 2", "\n")
print(outputs_1, "\n", weights_2, "\n", bias_2, "\n", outputs_2)
print("\n")
weights_3 = np.random.randint(0,2,(1,2)) ## weights - Hidden Layer 3
bias_3 = np.random.randint(0,2,(3,1)) ## bias - Hidden Layer 3
outputs_3 = np.dot(outputs_2, weights_3.T) + bias_2
print("Hidden Layer - 3", "\n")
print(outputs_2, "\n", weights_3, "\n", bias_3, "\n", outputs_3)
print("\n")


Hidden Layer - 1 

[[1 0 0 0]
 [0 1 1 0]
 [0 1 0 0]] 
 [[1 1 0 0]
 [1 1 0 0]
 [0 0 0 1]] 
 [[0]
 [1]
 [1]] 
 [[1 1 1]
 [2 2 2]
 [1 1 1]]


Hidden Layer - 2 

[[1 1 1]
 [2 2 2]
 [1 1 1]] 
 [[1 0 1]
 [0 1 1]] 
 [[0]
 [0]
 [1]] 
 [[2 2]
 [4 4]
 [3 3]]


Hidden Layer - 3 

[[2 2]
 [4 4]
 [3 3]] 
 [[1 0]] 
 [[0]
 [0]
 [0]] 
 [[2]
 [4]
 [4]]


